import type { ProviderConfig } from "./types";

export const PROVIDERS: ProviderConfig[] = [
  {
    id: "openrouter",
    name: "OpenRouter",
    baseURL: "https://openrouter.ai/api/v1",
    envKey: "OPENROUTER_API_KEY",
    headers: {
      "HTTP-Referer": "http://localhost:3000",
      "X-Title": "ChatGPT Clone",
    },
    models: [
      { id: "openai/gpt-oss-20b:free", name: "GPT-OSS 20B", description: "OpenAI open-weight, fast" },
      { id: "openai/gpt-oss-120b:free", name: "GPT-OSS 120B", description: "OpenAI open-weight, reasoning" },
      { id: "nvidia/nemotron-3-ultra-550b-a55b:free", name: "Nemotron 3 Ultra", description: "NVIDIA, 1M context" },
      { id: "nvidia/nemotron-3-super-120b-a12b:free", name: "Nemotron 3 Super", description: "NVIDIA MoE, 262K" },
      { id: "nvidia/nemotron-3.5-lightning:free", name: "Nemotron 3.5 Lightning", description: "NVIDIA, 1M, fast" },
      { id: "nvidia/nemotron-3-nano-30b-a3b:free", name: "Nemotron 3 Nano", description: "NVIDIA, 256K, efficient" },
      { id: "poolside/laguna-s-2.1:free", name: "Laguna S 2.1", description: "Poolside coding, 262K" },
      { id: "poolside/laguna-xs-2.1:free", name: "Laguna XS 2.1", description: "Poolside coding, fast" },
      { id: "google/gemma-4-31b-it:free", name: "Gemma 4 31B", description: "Google, 262K, vision" },
      { id: "google/gemma-4-26b-a4b-it:free", name: "Gemma 4 26B", description: "Google, 262K, multimodal" },
      { id: "cohere/north-mini-code:free", name: "North Mini Code", description: "Cohere coding, 256K" },
      { id: "z-ai/glm-5.2:free", name: "GLM 5.2", description: "Z.ai, 256K" },
      { id: "minimax/minimax-m3:free", name: "MiniMax M3", description: "MiniMax, 1M" },
      { id: "inclusionai/ling-3.0-flash:free", name: "Ling 3.0 Flash", description: "Fast general, 262K" },
      { id: "thinkingmachines/inkling:free", name: "Inkling", description: "Thinking Machines, 1M" },
      { id: "thinkingmachines/inkling-small:free", name: "Inkling Small", description: "Thinking Machines, fast" },
      { id: "dots-studio/dots-3-note-preview:free", name: "Dots3 Note", description: "Dots Studio, 512K" },
      { id: "openrouter/free", name: "Auto Router", description: "Picks best free model" },
    ],
  },
  {
    id: "kilo",
    name: "Kilo Gateway",
    baseURL: "https://api.kilo.ai/api/gateway",
    envKey: "KILO_API_KEY",
    models: [
      { id: "kilo-auto/free", name: "Kilo Auto Free", description: "Auto-router picks best free model" },
      { id: "nvidia/nemotron-3-ultra-550b-a55b:free", name: "Nemotron 3 Ultra", description: "NVIDIA, 1M" },
      { id: "nvidia/nemotron-3-super-120b-a12b:free", name: "Nemotron 3 Super", description: "NVIDIA MoE, 262K" },
      { id: "minimax/minimax-m3:free", name: "MiniMax M3", description: "MiniMax, 1M" },
      { id: "poolside/laguna-s-2.1:free", name: "Laguna S 2.1", description: "Poolside coding, 262K" },
      { id: "poolside/laguna-xs-2.1:free", name: "Laguna XS 2.1", description: "Poolside coding, fast" },
      { id: "cohere/north-mini-code:free", name: "North Mini Code", description: "Cohere coding, 256K" },
      { id: "stepfun/step-3.7-flash:free", name: "Step 3.7 Flash", description: "StepFun, 262K" },
      { id: "tencent/hy3:free", name: "Tencent Hy3", description: "Tencent, 262K" },
      { id: "inclusionai/ling-3.0-flash:free", name: "Ling 3.0 Flash", description: "Fast general, 262K" },
      { id: "dots-studio/dots-3-note-preview:free", name: "Dots3 Note", description: "Dots Studio, 512K" },
      { id: "liquid/lfm-2.5-2.6b:free", name: "LFM2.5 2.6B", description: "LiquidAI, 66K, fast" },
    ],
  },
  {
    id: "nvidia",
    name: "NVIDIA NIM",
    baseURL: "https://integrate.api.nvidia.com/v1",
    envKey: "NVIDIA_API_KEY",
    models: [
      { id: "nvidia/nemotron-3.5-lightning-30b-a3b", name: "Nemotron 3.5 Lightning", description: "NVIDIA, 1M, fast" },
      { id: "nvidia/nemotron-3-ultra-550b-a55b", name: "Nemotron 3 Ultra", description: "NVIDIA, 1M, flagship" },
      { id: "nvidia/nemotron-3-super-120b-a12b", name: "Nemotron 3 Super", description: "NVIDIA MoE, 262K" },
      { id: "nvidia/nemotron-3-nano-30b-a3b", name: "Nemotron 3 Nano", description: "NVIDIA, 256K, efficient" },
      { id: "nvidia/nemotron-nano-9b-v2", name: "Nemotron Nano 9B", description: "NVIDIA, 128K, lightweight" },
      { id: "nvidia/nemotron-nano-12b-v2-vl", name: "Nemotron Nano 12B VL", description: "NVIDIA, 128K, vision" },
    ],
  },
];
